### ISSUE TITLE
the Hlp-wiki-logo-medium.png was showing, but now it says it is missing

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/SocialPrescribingWiki#25]
![screenshot at 2018-11-06 14 46 40](https://user-images.githubusercontent.com/26943915/48079657-f08db280-e1d2-11e8-86b6-001b647528bd.png)

Have tried uploading it again, which confirmed it was already there, but still this error above

**Comment by tansaku** [comment]
this seems to have been fixed by getting the file system uploaded and connected #26
