### ISSUE TITLE
file system for uploads

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/SocialPrescribingWiki#26]
mediawiki stores file uploads on the file system - we'll need to have some shared drive or something available to the dokku instance to persist file uploads - we'll also need to migrate over the old files from production

**Comment by tansaku** [comment]
need dokku persistent storage:

https://github.com/dokku/dokku/blob/master/docs/advanced-usage/persistent-storage.md

**Comment by mattwr18** [comment]
Next steps:
1) @tansaku upload the `backup_file.tar` to `/var/lib/dokku/data/storage/mediawiki_official` as you have access to ssh into the box. 
2) Change Upload directory https://www.mediawiki.org/wiki/Manual:Configuring_file_uploads#Upload_directory
3) Verify permission are correct, as there need to be write permissions. 

Possibly missing something @tansaku?

**Comment by tansaku** [comment]
@mattwr18 does the upload directory need to be set in LocalSettings?

I guess there is also the question of unpacking the tar file in the right way - maybe best for us to do it together ...?

**Comment by tansaku** [comment]
pushing the archive up onto the remote:

```
[tansaku@Samuels-MacBook-Pro:~/Documents/Github/AgileVentures/SocialPrescribingWiki (master)]$ 
→ scp backup_files.tar hlp-ssh:~/
```

**Comment by tansaku** [comment]
solution for this from work with @mattwr18 and @mtc2013 is to set the config as follows:

```
$wgUploadDirectory  = "/storage/images"; 
$wgUploadPath       = "/images"; 
```
and then symlink internally as part of the dockerfile like so:

```
RUN mv /var/www/html/images /var/www/html/images-old
RUN ln -s /storage/images /var/www/html/images
```

**Comment by tansaku** [comment]
see https://github.com/AgileVentures/SocialPrescribingWiki/commit/1df595768b8f5077781a6fe55cd111d1b263924a
