### ISSUE TITLE
uploads not working sometimes

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/SocialPrescribingWiki#31]
@mattwr18 has encountered generic dokku upload fails when attempting uploads

**Comment by mattwr18** [comment]
Am able to upload smaller files like these:
https://develop-official.hlpwiki.agileventures.org/index.php/File:Pair-programming-2.jpg
https://develop-official.hlpwiki.agileventures.org/index.php/File:Capybara.jpeg
but when trying something like 1mb or larger get a 
![screenshot at 2018-11-12 15 49 11](https://user-images.githubusercontent.com/26943915/48365605-85d8ed00-e692-11e8-8064-6c990ddb1f27.png)

**Comment by tansaku** [comment]
hmm, interesting - maybe some settings we need to work on ... would be great to get more detailed logging ...

**Comment by mtc2013** [comment]
@tansaku we seem to have solved it
